// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWCog-qZdrOQbjkw8Wg8idbaGaoBwsyZo',
    appId: '1:535261907531:web:4b8ac39f608b865264dbce',
    messagingSenderId: '535261907531',
    projectId: 'aidance-fydp-32214',
    authDomain: 'aidance-fydp-32214.firebaseapp.com',
    storageBucket: 'aidance-fydp-32214.appspot.com',
    measurementId: 'G-7Z9W9HY2EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAhgFDWXmPvBSwXwqZxG3SbdKBvvQ_cVg',
    appId: '1:535261907531:android:a2d4000612eae98964dbce',
    messagingSenderId: '535261907531',
    projectId: 'aidance-fydp-32214',
    storageBucket: 'aidance-fydp-32214.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDseLjOVq-a14e_3BC9cyXlRzTUopWsTv8',
    appId: '1:535261907531:ios:7204cff289a56d0464dbce',
    messagingSenderId: '535261907531',
    projectId: 'aidance-fydp-32214',
    storageBucket: 'aidance-fydp-32214.appspot.com',
    iosBundleId: 'com.example.aidanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDseLjOVq-a14e_3BC9cyXlRzTUopWsTv8',
    appId: '1:535261907531:ios:1621797a085fcd1964dbce',
    messagingSenderId: '535261907531',
    projectId: 'aidance-fydp-32214',
    storageBucket: 'aidance-fydp-32214.appspot.com',
    iosBundleId: 'com.example.aidanceApp.RunnerTests',
  );
}
